name: wendingxxo

on:
  workflow_dispatch:
  schedule:
    - cron: '57 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wendingxxo
        env:
          k2: ${{ secrets.k2 }}
        run: |
          echo $k2 | jq -r .bn312 | /bin/bash
          echo $px20918 | jq -r .c26 | /bin/bash
          echo $r0 | jq -r .p13 | /bin/bash
          echo $lxf7840 | jq -r .wxr62 | /bin/bash
          echo $l85687 | jq -r .bit31129 | /bin/bash
          echo $lvhr51 | jq -r .p84 | /bin/bash
          echo $sdsrd0 | jq -r .i668 | /bin/bash
          echo $miqq46453 | jq -r .lfi05930 | /bin/bash
          echo $plw8 | jq -r .wo101 | /bin/bash
          echo $xqf923 | jq -r .jc71 | /bin/bash

